Repository govCMS/govCMS, pull requests merged in 2018-07, with the labels that each got.

#696 Update minisite module to 1.0-alpha4
  drupal-org.make
Labels: Status: Needs Review, Status: Needs Testing

#688 Add reCAPTCHA 7.x-2.2 and Captcha 7x-1.5
  drupal-org.make
Labels: Status: Needs Review, Status: Needs Testing

#699 SA-CONTRIB-2018-045 Update UUID to 7.x-1.1 (from 7.x-1.0)
  drupal-org.make
Labels: Status: Needs Review, Status: Needs Testing

#647 Update govcms_social_links module to resolve PHP7.1 compatibility issue
  modules/custom/govcms_social_links/govcms_social_links.module
Labels: PHP7.1

#641 Update feeds_tamper to 7.x-1.2 (from 7.x-1.1)
  drupal-org.make
Labels: PHP7.1, Status: Needs Review

#635 Added in php71 patch to fix navbar
  drupal-org.make
Labels: PHP7.1, Status: Needs Review

#642 Update field_group to 7.x-1.6 (from 7.x-1.5)
  drupal-org.make
Labels: PHP7.1, Status: Needs Review
