Repository govCMS/govCMS, pull requests merged in 2018-02, with the labels that each got.

#636 SA-CONTRIB-2018-013: Update entity to 7.x-1.9 (from 7.x-1.8)
  drupal-org.make
Labels: Priority: High, Testing: Passed (Functional)

#560 Update mimemail to 7.x-1.0 (from 7.x-1.0-beta4)
  drupal-org.make
Labels: PHP7.1, Status: Needs Testing

#626 Update Acquia Connector to 7.x-3.2 (from 7.x-3.1)
  drupal-org.make
Labels: Status: Needs Testing

#632 Add swiftmailer 7.x-1.7 and library v5.4.9
  drupal-org.make
  govcms.install
Labels: Status: Needs Testing

#616 Update webform to 7.x-4.16 (from 7.x-4.15)
  drupal-org.make
Labels: PHP7.1, Status: Needs Testing
