Repository govCMS/govCMS, pull requests merged in 2019-03, with the labels that each got.

#792 [SA-CONTRIB-2019-026] [7.x-2.x] Update services to 7.x-3.23 (from 7.x-3.20)
  drupal-org.make
Labels: Status: Needs Testing

#856 Update solr Dockerfile to be consistent with lagoon image
  .docker/Dockerfile.solr
Labels: Status: Needs Review

#842 [SA-CONTRIB-2019-034/035/036] Update views 7.x-3.21 (from 7.x-3.17)
  drupal-org.make
Labels: Status: Needs Testing

#858 [SA-CORE-2019-004] Update Drupal Core to 7.65
  drupal-org-core.make
Labels: Status: Needs Testing

#857 [GOVCMSD7-170] PHP7.2 compatibility patch for session_cookie_lifetime
  drupal-org.make
Labels: PHP7.2, Status: Needs Testing

#801 [GOVCMSD7-106] Update date 7.x-2.10 (from 7.x-2.9)
  drupal-org.make
Labels: PHP7.2, Status: Needs Testing
