Repository govCMS/govCMS, pull requests merged in 2019-05, with the labels that each got.

#827 [GOVCMSD7-132] Update redirect 7.x-1.0-rc3 (from 7.x-1.0-rc1)
  drupal-org.make
Labels: Status: Needs Review, Status: Needs Testing

#871 [GOVCMSD7-214] Update webform 7.x-4.19 (from 7.x-4.16)
  drupal-org.make
Labels: PHP7.2

#695 [7.x-3.x] add in TFA methods
  drupal-org.make
Labels: 7.x-3.x, Experimental
