Repository govCMS/GovCMS, pull requests merged in 2025-09, with the labels that each got.

#1591 [GOVCMSD11-275] Update drupal/migrate_plus module from 6.0.7 to 6.0.8
  composer.json
Labels: drupal11

#1539 [GOVCMSD11-234] Update drupal/migrate_tools module from 6.0.5 to 6.1.2
  composer.json
Labels: drupal11

#1622 [GOVCMSD11-306] Update drupal/facets module from 2.0.9 to 2.0.10 to fix security issues
  composer.json
Labels: drupal11

#1619 [GOVCMSD11-305] Add views_data_export module 8.x-1.6 to GovCMS Distribution
  composer.json
Labels: drupal11

#1618 [GOVCMSD11-304] Add drupal/search_api_spellcheck module to GovCMS Distribution
  composer.json
Labels: drupal11

#1626 [GOVCMSD11-157] Add drupal/book module to GovCMS distribution
  composer.json
Labels: drupal11

#1629 [GOVCMSD11-312] Update drupal/redirect module from 1.11.0 to 1.12.0
  composer.json
Labels: drupal11

#1639 [GOVCMSD11-316] Update drupal/token module from 1.15.0 to 1.16.0
  composer.json
Labels: drupal11

#1654 [GOVCMSD11-108 & GOVCMSD11-181] Update Lifecycle.php to mark modules as obsolete
  src/Modules/Lifecycle.php
Labels: blocked, drupal11

#1663 [GOVCMSD11-324] Applying patch for Entity Embed module due to 10.5/11.2 compatibility issue
  composer.json
Labels: drupal11

#1661 [GOVCMSD11-200] Switch default theme from GovCMS Bartik to Olivero
  config/install/system.theme.yml
  govcms.info.yml
  govcms.install
Labels: drupal11

#1664 [GOVCMSD11-164] Modify GovCMS README to align with D11 requirements
  DEVELOPMENT.md
  README.md
Labels: documentation, drupal11
